// Offline activation: a code is valid when its salted SHA-256 hash is in
// license-hashes.js (generated by scripts/generate-codes.mjs). The activation
// is stored locally as that hash, never as the code itself.
import { LICENSE_SALT, LICENSE_HASHES } from './license-hashes.js';

const PREFIX = 'MOB';
const CODE_LEN = 16;
const VALID = new Set(LICENSE_HASHES);

export function normalizeCode(code) {
  let s = String(code || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (s.startsWith(PREFIX) && s.length === PREFIX.length + CODE_LEN) s = s.slice(PREFIX.length);
  return s;
}

export async function hashCode(code) {
  const data = new TextEncoder().encode(`${LICENSE_SALT}:${normalizeCode(code)}`);
  const digest = await crypto.subtle.digest('SHA-256', data);
  return [...new Uint8Array(digest)].map(b => b.toString(16).padStart(2, '0')).join('');
}

export async function isActivated() {
  const { license } = await chrome.storage.local.get('license');
  return !!license?.hash && VALID.has(license.hash);
}

export async function activate(code) {
  if (normalizeCode(code).length !== CODE_LEN) {
    throw new Error('Kod ma format MOB-XXXX-XXXX-XXXX-XXXX.');
  }
  const hash = await hashCode(code);
  if (!VALID.has(hash)) throw new Error('Nieprawidłowy kod aktywacyjny.');
  await chrome.storage.local.set({ license: { hash, activatedAt: new Date().toISOString() } });
}

export async function deactivate() {
  await chrome.storage.local.remove('license');
}
