// Generates activation codes for the extension.
//
// Only salted SHA-256 hashes go into the extension (extension/src/license-hashes.js),
// the plain codes are written to a file OUTSIDE the repo (or a gitignored one):
// this repository is public, so never commit the codes themselves.
//
// Usage:
//   node scripts/generate-codes.mjs --out ~/codes.txt            # new set of 100 codes (invalidates old ones)
//   node scripts/generate-codes.mjs --count 50 --append --out f  # add 50 codes, keep existing ones valid
import { createHash, randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// No 0/O or 1/I, so codes can be typed without guessing.
export const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
export const PREFIX = 'MOB';
const GROUPS = 4;
const GROUP_LEN = 4; // 16 chars x 5 bits = 80 bits of randomness

export function normalizeCode(code) {
  let s = String(code || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
  if (s.startsWith(PREFIX) && s.length === PREFIX.length + GROUPS * GROUP_LEN) s = s.slice(PREFIX.length);
  return s;
}

export function hashCode(salt, code) {
  return createHash('sha256').update(`${salt}:${normalizeCode(code)}`).digest('hex');
}

function randomCode() {
  const bytes = randomBytes(GROUPS * GROUP_LEN);
  const chars = [...bytes].map(b => ALPHABET[b % ALPHABET.length]); // 256 % 32 === 0: unbiased
  const groups = [];
  for (let i = 0; i < GROUPS; i++) groups.push(chars.slice(i * GROUP_LEN, (i + 1) * GROUP_LEN).join(''));
  return `${PREFIX}-${groups.join('-')}`;
}

const HASHES_FILE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'extension', 'src', 'license-hashes.js');

function readExisting() {
  if (!existsSync(HASHES_FILE)) return null;
  const src = readFileSync(HASHES_FILE, 'utf8');
  const salt = /LICENSE_SALT = '([0-9a-f]+)'/.exec(src)?.[1];
  const hashes = [...src.matchAll(/'([0-9a-f]{64})'/g)].map(m => m[1]);
  return salt ? { salt, hashes } : null;
}

function main() {
  const args = process.argv.slice(2);
  const opt = name => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : undefined; };
  const count = Number(opt('--count') || 100);
  const out = opt('--out');
  if (!out) {
    console.error('Podaj plik na kody: --out <ścieżka poza repozytorium>');
    process.exit(1);
  }
  const existing = args.includes('--append') ? readExisting() : null;
  const salt = existing?.salt || randomBytes(16).toString('hex');
  const hashes = new Set(existing?.hashes || []);
  const codes = [];
  while (codes.length < count) {
    const code = randomCode();
    const h = hashCode(salt, code);
    if (hashes.has(h)) continue;
    hashes.add(h);
    codes.push(code);
  }

  const list = [...hashes].sort();
  writeFileSync(HASHES_FILE, `// GENERATED by scripts/generate-codes.mjs - do not edit by hand.
// Salted SHA-256 hashes of valid activation codes. The codes themselves are
// never stored in this repository.
export const LICENSE_SALT = '${salt}';

export const LICENSE_HASHES = [
${list.map(h => `  '${h}'`).join(',\n')}
];
`);
  writeFileSync(out, codes.join('\n') + '\n', { flag: existing ? 'a' : 'w' });
  console.log(`${codes.length} kodów zapisano do ${out}; łącznie ważnych kodów: ${list.length}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
